--- !ruby/object:Jumpstart::Configuration
application_name: NorthStream Live
business_name: NorthStream Productions
domain: example.com
support_email: northstream@revamp.dev
default_from_email: Jumpstart <support@example.com>
business_address: ''
background_job_processor: sidekiq
email_provider: ''
personal_accounts: true
livereload: true
solargraph: true
register_with_account: false
multitenancy:
- subdomain
- domain
payment_processors:
- stripe
