--- !ruby/object:Jumpstart::Configuration
application_name: NorthStream Live
business_name: NorthStream Productions
domain: nortstream.live
support_email: northstream@revamp.dev
default_from_email: NorthStream Live <info@northstream.live>
business_address: ''
background_job_processor: sidekiq
email_provider: mailgun
personal_accounts: true
livereload: true
solargraph: true
register_with_account: false
multitenancy:
- subdomain
- domain
payment_processors:
- stripe
